export const template_gl92631048 = {
  result: {
    pagination: null,
    accountName: 'e-Commerce Test Customer-BR180',
    createdByUser: {
      firstName: 'beckyF',
      lastName: 'beckyL',
      emailAddress: null,
      cartLineItems: null,
      internalUser: false,
      rewardsEligible: false,
      lastSelectedAccount: null,
      profileId: null,
      userType: null,
      accountBranch: null,
    },
    lastModifiedDate: '05-18-2023',
    templateName: 'shelleytest0519',
    templateItems: [
      {
        itemNumber: '351692',
        itemType: null,
        sendToMincronDirectly: false,
        vendorColorId: null,
        pdpUrl:
          '/productDetail/C-351614?skuId=351692&Color=Weathered+Wood&Dimension=13-1%2F4%22+x+39-3%2F8%22',
        available: true,
        description: null,
        productOrItemNumber: 'C-351614',
        subTotal: 0,
        productOrItemDescription: null,
        multiVariationData: {
          singleVariationDisplay: {
            color: 'Charcoal',
            size: '13-1/4" x 39-3/8"',
          },
          allOptionsSingle: false,
          skus: {
            '351669': {
              color: ['Charcoal'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '351678': {
              color: ['Shakewood'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '351679': {
              color: ['Slate'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '351692': {
              color: ['Weathered Wood'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
          },
          defaultSkuId: '351679',
          currentVendorColorId: null,
          variationKeyColor: 'color',
          vendorColors: [],
          variationGroups: [
            {
              variationTypes: ['color'],
            },
            {
              variationTypes: ['size'],
            },
          ],
          variations: {
            color: {
              Shakewood: ['351678'],
              'Weathered Wood': ['351692'],
              Slate: ['351679'],
              Charcoal: ['351669'],
            },
            size: {
              '13-1/4" x 39-3/8"': ['351679', '351678', '351692', '351669'],
            },
          },
          variationKeyMFG: 'MFG',
          availableVariationCount: 1,
          highestPrioritySku: null,
          singleColorDisplay: 'Charcoal',
          validSkuIdsMap: {},
          maxVariationGroupSize: 1,
          allVariationTypes: ['color', 'size'],
          currentVariations: {
            color: 'Weathered Wood',
            size: '13-1/4" x 39-3/8"',
          },
          currentSkuId: '351692',
          variationSteps: {
            showStep1: true,
            step2: {
              size: {
                '13-1/4" x 39-3/8"': ['351679', '351692', '351678', '351669'],
              },
            },
            showStep2: true,
            step1: {
              color: {
                Shakewood: ['351678'],
                'Weathered Wood': ['351692'],
                Slate: ['351679'],
                Charcoal: ['351669'],
              },
              MFG: null,
            },
          },
        },
        skusVariation: null,
        variations: null,
        imageUrl: {
          thumbnail: '/images/large/351692_default_thumb.jpg',
          large: '/images/large/351692_default.jpg',
          swatch: '/images/large/351692_default_swatch.jpg',
        },
        productImageUrl: '/images/large/351692_default_thumb.jpg',
        unitPrice: 48.03,
        itemUnitPrice: 0,
        quantity: 1,
        itemOrProductDescription:
          'GAF 13-1/4" x 39-3/8" Timberline Ultra HD&reg; Shingles with StainGuard Protection Weathered Wood',
        unitOfMeasure: 'BDL',
        nickName: null,
        templateItemId: 'gi20420009',
        productOnErrorImageUrl: '/images/large/brand/gaf_brand_thumb.jpg',
        productNumber: null,
        defaultUnitOfMeasure: 'BDL',
        internalProductName:
          'Timberline Ultra HD&reg; Shingles with StainGuard Protection',
        ATGItemMapping: null,
        itemSubTotal: 0,
        nonStockItem: false,
        sendDescriptionOnlyToMincron: false,
        lineComments: null,
        extendedDescription: null,
        hasBranchAvailability: false,
      },
      {
        itemNumber: '351669',
        itemType: null,
        sendToMincronDirectly: false,
        vendorColorId: null,
        pdpUrl:
          '/productDetail/C-351614?skuId=351669&Color=Charcoal&Dimension=13-1%2F4%22+x+39-3%2F8%22',
        available: true,
        description: null,
        productOrItemNumber: 'C-351614',
        subTotal: 0,
        productOrItemDescription: null,
        multiVariationData: {
          singleVariationDisplay: {
            color: 'Charcoal',
            size: '13-1/4" x 39-3/8"',
          },
          allOptionsSingle: false,
          skus: {
            '351669': {
              color: ['Charcoal'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '351678': {
              color: ['Shakewood'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '351679': {
              color: ['Slate'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '351692': {
              color: ['Weathered Wood'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
          },
          defaultSkuId: '351679',
          currentVendorColorId: null,
          variationKeyColor: 'color',
          vendorColors: [],
          variationGroups: [
            {
              variationTypes: ['color'],
            },
            {
              variationTypes: ['size'],
            },
          ],
          variations: {
            color: {
              Shakewood: ['351678'],
              'Weathered Wood': ['351692'],
              Slate: ['351679'],
              Charcoal: ['351669'],
            },
            size: {
              '13-1/4" x 39-3/8"': ['351679', '351678', '351692', '351669'],
            },
          },
          variationKeyMFG: 'MFG',
          availableVariationCount: 1,
          highestPrioritySku: null,
          singleColorDisplay: 'Charcoal',
          validSkuIdsMap: {},
          maxVariationGroupSize: 1,
          allVariationTypes: ['color', 'size'],
          currentVariations: {
            color: 'Charcoal',
            size: '13-1/4" x 39-3/8"',
          },
          currentSkuId: '351669',
          variationSteps: {
            showStep1: true,
            step2: {
              size: {
                '13-1/4" x 39-3/8"': ['351679', '351678', '351692', '351669'],
              },
            },
            showStep2: true,
            step1: {
              color: {
                Shakewood: ['351678'],
                'Weathered Wood': ['351692'],
                Slate: ['351679'],
                Charcoal: ['351669'],
              },
              MFG: null,
            },
          },
        },
        skusVariation: null,
        variations: null,
        imageUrl: {
          thumbnail: '/images/large/351669_default_thumb.jpg',
          large: '/images/large/351669_default.jpg',
          swatch: '/images/large/351669_default_swatch.jpg',
        },
        productImageUrl: '/images/large/351669_default_thumb.jpg',
        unitPrice: 48.03,
        itemUnitPrice: 0,
        quantity: 1,
        itemOrProductDescription:
          'GAF 13-1/4" x 39-3/8" Timberline Ultra HD&reg; Shingles with StainGuard Protection Charcoal',
        unitOfMeasure: 'BDL',
        nickName: null,
        templateItemId: 'gi20420008',
        productOnErrorImageUrl: '/images/large/brand/gaf_brand_thumb.jpg',
        productNumber: null,
        defaultUnitOfMeasure: 'BDL',
        internalProductName:
          'Timberline Ultra HD&reg; Shingles with StainGuard Protection',
        ATGItemMapping: null,
        itemSubTotal: 0,
        nonStockItem: false,
        sendDescriptionOnlyToMincron: false,
        lineComments: null,
        extendedDescription: null,
        hasBranchAvailability: false,
      },
    ],
    accountLegacyId: '280381',
    isAccountClosed: false,
    lastModifiedUser: {
      firstName: 'beckyF',
      lastName: 'beckyL',
      emailAddress: null,
      cartLineItems: null,
      internalUser: false,
      rewardsEligible: false,
      lastSelectedAccount: null,
      profileId: null,
      userType: null,
      accountBranch: null,
    },
    templateId: 'gl92631048',
  },
};

export const template_gl92501052 = {
  result: {
    pagination: null,
    accountName: 'e-Commerce Test Customer-BR180',
    createdByUser: {
      firstName: 'beckyF',
      lastName: 'beckyL',
      emailAddress: null,
      cartLineItems: null,
      internalUser: false,
      rewardsEligible: false,
      lastSelectedAccount: null,
      profileId: null,
      userType: null,
      accountBranch: null,
    },
    lastModifiedDate: '05-09-2023',
    templateName: '0509 BECKY AAA aaa',
    templateItems: [
      {
        itemNumber: '413339',
        itemType: null,
        sendToMincronDirectly: false,
        vendorColorId: null,
        pdpUrl: '/productDetail/C-428596?skuId=413339&Color=Teak',
        available: true,
        description: null,
        productOrItemNumber: 'C-428596',
        subTotal: 0,
        productOrItemDescription: null,
        multiVariationData: {
          singleVariationDisplay: {
            color: 'Antique Silver',
          },
          allOptionsSingle: false,
          skus: {
            '413334': {
              color: ['Brownwood'],
            },
            '413335': {
              color: ['Desert Tan'],
            },
            '413336': {
              color: ['Driftwood'],
            },
            '413337': {
              color: ['Estate Grey'],
            },
            '413338': {
              color: ['Onyx Black'],
            },
            '413339': {
              color: ['Teak'],
            },
            '428596': {
              color: ['Antique Silver'],
            },
          },
          defaultSkuId: '413338',
          currentVendorColorId: null,
          variationKeyColor: 'color',
          vendorColors: [],
          variationGroups: [
            {
              variationTypes: ['color'],
            },
          ],
          variations: {
            color: {
              'Estate Grey': ['413337'],
              'Onyx Black': ['413338'],
              Brownwood: ['413334'],
              'Antique Silver': ['428596'],
              Driftwood: ['413336'],
              Teak: ['413339'],
              'Desert Tan': ['413335'],
            },
          },
          variationKeyMFG: 'MFG',
          availableVariationCount: 1,
          highestPrioritySku: null,
          singleColorDisplay: 'Antique Silver',
          validSkuIdsMap: {},
          maxVariationGroupSize: 1,
          allVariationTypes: ['color'],
          currentVariations: {
            color: 'Teak',
          },
          currentSkuId: '413339',
          variationSteps: {
            showStep1: true,
            step2: {},
            showStep2: false,
            step1: {
              color: {
                'Estate Grey': ['413337'],
                'Onyx Black': ['413338'],
                Brownwood: ['413334'],
                'Antique Silver': ['428596'],
                Driftwood: ['413336'],
                Teak: ['413339'],
                'Desert Tan': ['413335'],
              },
              MFG: null,
            },
          },
        },
        skusVariation: null,
        variations: null,
        imageUrl: {
          thumbnail: '/images/large/413339_default_thumb.jpg',
          large: '/images/large/413339_default.jpg',
          swatch: '/images/large/413339_default_swatch.jpg',
        },
        productImageUrl: '/images/large/413339_default_thumb.jpg',
        unitPrice: 49.17,
        itemUnitPrice: 0,
        quantity: 20,
        itemOrProductDescription:
          'Owens Corning Duration&reg; STORM&reg; TruDefinition&reg; Shingles Teak',
        unitOfMeasure: 'BDL',
        nickName: null,
        templateItemId: 'gi20340014',
        productOnErrorImageUrl:
          '/images/large/brand/owens_corning_brand_thumb.jpg',
        productNumber: null,
        defaultUnitOfMeasure: 'BDL',
        internalProductName:
          'Duration&reg; STORM&reg; TruDefinition&reg; Shingles',
        ATGItemMapping: null,
        itemSubTotal: 0,
        nonStockItem: false,
        sendDescriptionOnlyToMincron: false,
        lineComments: null,
        extendedDescription: null,
        hasBranchAvailability: true,
      },
      {
        itemNumber: '555608',
        itemType: null,
        sendToMincronDirectly: false,
        vendorColorId: null,
        pdpUrl:
          '/productDetail/C-555601?skuId=555608&Color=59&Dimension=12%22+x+18%22',
        available: true,
        description: null,
        productOrItemNumber: 'C-555601',
        subTotal: 0,
        productOrItemDescription: null,
        multiVariationData: {
          singleVariationDisplay: {
            color: 'Arbor Blend(200)',
            size: '12" x 18"',
            MFG: 'Allura ',
          },
          allOptionsSingle: false,
          skus: {
            '555601': {
              color: [
                'White Birch(1)',
                'White(1)',
                'Dover White(1)',
                'Bright White(1)',
              ],
              size: ['12" x 18"'],
              width: ['12"'],
              length: ['18"'],
              MFG: [
                'Quality Edge',
                'KP',
                'Cellwood',
                'Variform',
                'RMC',
                'Mastic',
              ],
            },
            '555606': {
              color: [
                'Birchwood(34)',
                'Eggshell(34)',
                'Pearl(34)',
                'Cottage White(34)',
                'Beige(34)',
                'Sandstone Beige(34)',
              ],
              size: ['12" x 18"'],
              width: ['12"'],
              length: ['18"'],
              MFG: [
                'Certainteed',
                'Heartland-Provia',
                'EP',
                'Foundry',
                'Norandex',
                'Rollex',
              ],
            },
            '555608': {
              color: [
                'Smoke(59)',
                'Castle Stone(59)',
                'Stratus(59)',
                'Weather Blend/Heather(59)',
                'Greystone(59)',
                'Graphite Grey(59)',
                'Cape Cod Grey(59)',
                'Charcoal Grey(59)',
              ],
              size: ['12" x 18"'],
              width: ['12"'],
              length: ['18"'],
              MFG: [
                'Certainteed',
                'Mitten',
                'CT Vytec',
                'RMC',
                'EP',
                'Norandex',
                'Mastic',
              ],
            },
            '555609': {
              color: ['Wheat(65)'],
              size: ['12" x 18"'],
              width: ['12"'],
              length: ['18"'],
              MFG: ['EP'],
            },
            '555616': {
              color: [
                'Arbor Blend(200)',
                'Meadow(200)',
                'Sage(200)',
                'Mountain Laurel(200)',
                'Cypress(200)',
              ],
              size: ['12" x 18"'],
              width: ['12"'],
              length: ['18"'],
              MFG: ['Certainteed', 'Quality Edge', 'KP', 'RMC', 'EP'],
            },
            '555692': {
              color: [
                'White Birch(1)',
                'White(1)',
                'Dover White(1)',
                'Bright White(1)',
              ],
              size: ['18" x 24"'],
              width: ['18"'],
              length: ['24"'],
              MFG: [
                'Quality Edge',
                'KP',
                'Cellwood',
                'Variform',
                'RMC',
                'Mastic',
              ],
            },
            '555695': {
              color: [
                'Country Beige(11)',
                'Summer Suede(11)',
                'Sierra Brown(11)',
              ],
              size: ['18" x 24"'],
              width: ['18"'],
              length: ['24"'],
              MFG: ['Quality Edge', 'CT Vytec', 'EP'],
            },
            '555698': {
              color: [
                'Birchwood(34)',
                'Eggshell(34)',
                'Pearl(34)',
                'Cottage White(34)',
                'Beige(34)',
                'Sandstone Beige(34)',
              ],
              size: ['18" x 24"'],
              width: ['18"'],
              length: ['24"'],
              MFG: [
                'Certainteed',
                'Heartland-Provia',
                'EP',
                'Foundry',
                'Norandex',
                'Rollex',
              ],
            },
            '555700': {
              color: [
                'Smoke(59)',
                'Castle Stone(59)',
                'Stratus(59)',
                'Weather Blend/Heather(59)',
                'Greystone(59)',
                'Graphite Grey(59)',
                'Cape Cod Grey(59)',
                'Charcoal Grey(59)',
              ],
              size: ['18" x 24"'],
              width: ['18"'],
              length: ['24"'],
              MFG: [
                'Certainteed',
                'Mitten',
                'CT Vytec',
                'RMC',
                'EP',
                'Norandex',
                'Mastic',
              ],
            },
            '555701': {
              color: ['Wheat(65)'],
              size: ['18" x 24"'],
              width: ['18"'],
              length: ['24"'],
              MFG: ['EP'],
            },
            '555704': {
              color: [
                'Taupe(97)',
                'Cypress(97)',
                'Misty Taupe(97)',
                'Clay(97)',
                'Pebble Clay(97)',
                'Natural Clay(97)',
              ],
              size: ['18" x 24"'],
              width: ['18"'],
              length: ['24"'],
              MFG: [
                'Quality Edge',
                'Allura ',
                'KP',
                'EP',
                'Norandex',
                'Georgia Pacific',
                'CT Wolverine',
              ],
            },
            '555706': {
              color: [
                'Arbor Blend(200)',
                'Meadow(200)',
                'Sage(200)',
                'Mountain Laurel(200)',
                'Cypress(200)',
              ],
              size: ['18" x 24"'],
              width: ['18"'],
              length: ['24"'],
              MFG: ['Certainteed', 'Quality Edge', 'KP', 'RMC', 'EP'],
            },
            '557620': {
              color: [
                'Stone Mountain Clay(8)',
                'Clay(8)',
                'Autumn Leaf(8)',
                'Rustic Clay(8)',
                'Desert Clay(8)',
                'Shadow(8)',
                'Claytone(8)',
                'Sierra(8)',
                'Pebble(8)',
                'Khaki(8)',
                'Natural Clay(8)',
              ],
              size: ['12" x 18"'],
              width: ['12"'],
              length: ['18"'],
              MFG: [
                'Exteria',
                'Quality Edge',
                'Gentek CA',
                'Gentek/Revere',
                'Cellwood',
                'Variform',
                'CT Vytec',
                'Foundry',
                'Norandex',
                'Edco',
                'Rollex',
              ],
            },
            '557625': {
              color: ['Sterling Grey/Silverplate(16)', 'Victorian Grey(16)'],
              size: ['12" x 18"'],
              width: ['12"'],
              length: ['18"'],
              MFG: ['Certainteed', 'Quality Edge'],
            },
            '557633': {
              color: ['Paintable(30)'],
              size: ['12" x 18"'],
              width: ['12"'],
              length: ['18"'],
              MFG: ['TRI-BUILT'],
            },
            '557638': {
              color: [
                'Desert Sand(48)',
                'Natural Oak(48)',
                'Sahara(48)',
                'Sand(48)',
                'Sand Dune(48)',
              ],
              size: ['12" x 18"'],
              width: ['12"'],
              length: ['18"'],
              MFG: [
                'KP',
                'Cellwood',
                'Royal Building Products',
                'Foundry',
                'Norandex',
                'Mastic',
              ],
            },
            '557946': {
              color: [
                'Stone Mountain Clay(8)',
                'Clay(8)',
                'Autumn Leaf(8)',
                'Rustic Clay(8)',
                'Desert Clay(8)',
                'Shadow(8)',
                'Claytone(8)',
                'Sierra(8)',
                'Pebble(8)',
                'Khaki(8)',
                'Natural Clay(8)',
              ],
              size: ['18" x 24"'],
              width: ['18"'],
              length: ['24"'],
              MFG: [
                'Exteria',
                'Quality Edge',
                'Gentek CA',
                'Gentek/Revere',
                'Cellwood',
                'Variform',
                'CT Vytec',
                'Foundry',
                'Norandex',
                'Edco',
                'Rollex',
              ],
            },
            '557950': {
              color: ['Sterling Grey/Silverplate(16)', 'Victorian Grey(16)'],
              size: ['18" x 24"'],
              width: ['18"'],
              length: ['24"'],
              MFG: ['Certainteed', 'Quality Edge'],
            },
            '557957': {
              color: ['Paintable(30)'],
              size: ['18" x 24"'],
              width: ['18"'],
              length: ['24"'],
              MFG: ['TRI-BUILT'],
            },
            '557961': {
              color: [
                'Desert Sand(48)',
                'Natural Oak(48)',
                'Sahara(48)',
                'Sand(48)',
                'Sand Dune(48)',
              ],
              size: ['18" x 24"'],
              width: ['18"'],
              length: ['24"'],
              MFG: [
                'KP',
                'Cellwood',
                'Royal Building Products',
                'Foundry',
                'Norandex',
                'Mastic',
              ],
            },
          },
          defaultSkuId: '557950',
          currentVendorColorId: null,
          variationKeyColor: 'color',
          vendorColors: [
            {
              color: 'Weather Blend/Heather(59)',
              name: 'Weather Blend/Heather',
              id: '705977',
              sku: '555608',
              MFG: 'Certainteed',
            },
            {
              color: 'Greystone(59)',
              name: 'Greystone',
              id: '705978',
              sku: '555608',
              MFG: 'EP',
            },
            {
              color: 'Cape Cod Grey(59)',
              name: 'Cape Cod Grey',
              id: '705979',
              sku: '555608',
              MFG: 'Mastic',
            },
            {
              color: 'Stratus(59)',
              name: 'Stratus',
              id: '705980',
              sku: '555608',
              MFG: 'Mitten',
            },
            {
              color: 'Castle Stone(59)',
              name: 'Castle Stone',
              id: '705981',
              sku: '555608',
              MFG: 'CT Vytec',
            },
            {
              color: 'Graphite Grey(59)',
              name: 'Graphite Grey',
              id: '705982',
              sku: '555608',
              MFG: 'RMC',
            },
            {
              color: 'Charcoal Grey(59)',
              name: 'Charcoal Grey',
              id: '705983',
              sku: '555608',
              MFG: 'RMC',
            },
            {
              color: 'Smoke(59)',
              name: 'Smoke',
              id: '705984',
              sku: '555608',
              MFG: 'Norandex',
            },
            {
              color: 'Wheat(65)',
              name: 'Wheat',
              id: '706245',
              sku: '555701',
              MFG: 'EP',
            },
            {
              color: 'Sterling Grey/Silverplate(16)',
              name: 'Sterling Grey/Silverplate',
              id: '702893',
              sku: '557950',
              MFG: 'Certainteed',
            },
            {
              color: 'Victorian Grey(16)',
              name: 'Victorian Grey',
              id: '702894',
              sku: '557950',
              MFG: 'Quality Edge',
            },
            {
              color: 'Paintable(30)',
              name: 'Paintable',
              id: '704614',
              sku: '557633',
              MFG: 'TRI-BUILT',
            },
            {
              color: 'Clay(97)',
              name: 'Clay',
              id: '708215',
              sku: '555704',
              MFG: 'EP',
            },
            {
              color: 'Clay(97)',
              name: 'Clay',
              id: '708216',
              sku: '555704',
              MFG: 'KP',
            },
            {
              color: 'Natural Clay(97)',
              name: 'Natural Clay',
              id: '708217',
              sku: '555704',
              MFG: 'CT Wolverine',
            },
            {
              color: 'Pebble Clay(97)',
              name: 'Pebble Clay',
              id: '708218',
              sku: '555704',
              MFG: 'Quality Edge',
            },
            {
              color: 'Clay(97)',
              name: 'Clay',
              id: '708219',
              sku: '555704',
              MFG: 'Georgia Pacific',
            },
            {
              color: 'Taupe(97)',
              name: 'Taupe',
              id: '708220',
              sku: '555704',
              MFG: 'Allura ',
            },
            {
              color: 'Cypress(97)',
              name: 'Cypress',
              id: '708221',
              sku: '555704',
              MFG: 'Norandex',
            },
            {
              color: 'Misty Taupe(97)',
              name: 'Misty Taupe',
              id: '708222',
              sku: '555704',
              MFG: 'Norandex',
            },
            {
              color: 'Weather Blend/Heather(59)',
              name: 'Weather Blend/Heather',
              id: '706153',
              sku: '555700',
              MFG: 'Certainteed',
            },
            {
              color: 'Greystone(59)',
              name: 'Greystone',
              id: '706154',
              sku: '555700',
              MFG: 'EP',
            },
            {
              color: 'Cape Cod Grey(59)',
              name: 'Cape Cod Grey',
              id: '706155',
              sku: '555700',
              MFG: 'Mastic',
            },
            {
              color: 'Stratus(59)',
              name: 'Stratus',
              id: '706156',
              sku: '555700',
              MFG: 'Mitten',
            },
            {
              color: 'Castle Stone(59)',
              name: 'Castle Stone',
              id: '706157',
              sku: '555700',
              MFG: 'CT Vytec',
            },
            {
              color: 'Graphite Grey(59)',
              name: 'Graphite Grey',
              id: '706158',
              sku: '555700',
              MFG: 'RMC',
            },
            {
              color: 'Charcoal Grey(59)',
              name: 'Charcoal Grey',
              id: '706159',
              sku: '555700',
              MFG: 'RMC',
            },
            {
              color: 'Smoke(59)',
              name: 'Smoke',
              id: '706160',
              sku: '555700',
              MFG: 'Norandex',
            },
            {
              color: 'Wheat(65)',
              name: 'Wheat',
              id: '706227',
              sku: '555609',
              MFG: 'EP',
            },
            {
              color: 'Sand(48)',
              name: 'Sand',
              id: '705679',
              sku: '557961',
              MFG: 'Cellwood',
            },
            {
              color: 'Desert Sand(48)',
              name: 'Desert Sand',
              id: '705680',
              sku: '557961',
              MFG: 'Mastic',
            },
            {
              color: 'Natural Oak(48)',
              name: 'Natural Oak',
              id: '705681',
              sku: '557961',
              MFG: 'KP',
            },
            {
              color: 'Sand(48)',
              name: 'Sand',
              id: '705682',
              sku: '557961',
              MFG: 'Royal Building Products',
            },
            {
              color: 'Sahara(48)',
              name: 'Sahara',
              id: '705683',
              sku: '557961',
              MFG: 'Foundry',
            },
            {
              color: 'Sand Dune(48)',
              name: 'Sand Dune',
              id: '705684',
              sku: '557961',
              MFG: 'Norandex',
            },
            {
              color: 'Country Beige(11)',
              name: 'Country Beige',
              id: '702557',
              sku: '555695',
              MFG: 'EP',
            },
            {
              color: 'Sierra Brown(11)',
              name: 'Sierra Brown',
              id: '702558',
              sku: '555695',
              MFG: 'CT Vytec',
            },
            {
              color: 'Summer Suede(11)',
              name: 'Summer Suede',
              id: '702559',
              sku: '555695',
              MFG: 'Quality Edge',
            },
            {
              color: 'Khaki(8)',
              name: 'Khaki',
              id: '702000',
              sku: '557946',
              MFG: 'Cellwood',
            },
            {
              color: 'Desert Clay(8)',
              name: 'Desert Clay',
              id: '702001',
              sku: '557946',
              MFG: 'Exteria',
            },
            {
              color: 'Pebble(8)',
              name: 'Pebble',
              id: '702002',
              sku: '557946',
              MFG: 'Gentek CA',
            },
            {
              color: 'Pebble(8)',
              name: 'Pebble',
              id: '702003',
              sku: '557946',
              MFG: 'Gentek/Revere',
            },
            {
              color: 'Stone Mountain Clay(8)',
              name: 'Stone Mountain Clay',
              id: '702004',
              sku: '557946',
              MFG: 'Variform',
            },
            {
              color: 'Rustic Clay(8)',
              name: 'Rustic Clay',
              id: '702005',
              sku: '557946',
              MFG: 'CT Vytec',
            },
            {
              color: 'Clay(8)',
              name: 'Clay',
              id: '702006',
              sku: '557946',
              MFG: 'Rollex',
            },
            {
              color: 'Pebble(8)',
              name: 'Pebble',
              id: '702007',
              sku: '557946',
              MFG: 'Rollex',
            },
            {
              color: 'Autumn Leaf(8)',
              name: 'Autumn Leaf',
              id: '702008',
              sku: '557946',
              MFG: 'Quality Edge',
            },
            {
              color: 'Shadow(8)',
              name: 'Shadow',
              id: '702009',
              sku: '557946',
              MFG: 'Foundry',
            },
            {
              color: 'Natural Clay(8)',
              name: 'Natural Clay',
              id: '702010',
              sku: '557946',
              MFG: 'Foundry',
            },
            {
              color: 'Sierra(8)',
              name: 'Sierra',
              id: '702011',
              sku: '557946',
              MFG: 'Norandex',
            },
            {
              color: 'Claytone(8)',
              name: 'Claytone',
              id: '702012',
              sku: '557946',
              MFG: 'Edco',
            },
            {
              color: 'Paintable(30)',
              name: 'Paintable',
              id: '704686',
              sku: '557957',
              MFG: 'TRI-BUILT',
            },
            {
              color: 'Khaki(8)',
              name: 'Khaki',
              id: '701142',
              sku: '557620',
              MFG: 'Cellwood',
            },
            {
              color: 'Desert Clay(8)',
              name: 'Desert Clay',
              id: '701143',
              sku: '557620',
              MFG: 'Exteria',
            },
            {
              color: 'Pebble(8)',
              name: 'Pebble',
              id: '701144',
              sku: '557620',
              MFG: 'Gentek CA',
            },
            {
              color: 'Pebble(8)',
              name: 'Pebble',
              id: '701145',
              sku: '557620',
              MFG: 'Gentek/Revere',
            },
            {
              color: 'Stone Mountain Clay(8)',
              name: 'Stone Mountain Clay',
              id: '701146',
              sku: '557620',
              MFG: 'Variform',
            },
            {
              color: 'Rustic Clay(8)',
              name: 'Rustic Clay',
              id: '701147',
              sku: '557620',
              MFG: 'CT Vytec',
            },
            {
              color: 'Clay(8)',
              name: 'Clay',
              id: '701148',
              sku: '557620',
              MFG: 'Rollex',
            },
            {
              color: 'Pebble(8)',
              name: 'Pebble',
              id: '701149',
              sku: '557620',
              MFG: 'Rollex',
            },
            {
              color: 'Autumn Leaf(8)',
              name: 'Autumn Leaf',
              id: '701150',
              sku: '557620',
              MFG: 'Quality Edge',
            },
            {
              color: 'Shadow(8)',
              name: 'Shadow',
              id: '701151',
              sku: '557620',
              MFG: 'Foundry',
            },
            {
              color: 'Natural Clay(8)',
              name: 'Natural Clay',
              id: '701152',
              sku: '557620',
              MFG: 'Foundry',
            },
            {
              color: 'Sierra(8)',
              name: 'Sierra',
              id: '701153',
              sku: '557620',
              MFG: 'Norandex',
            },
            {
              color: 'Claytone(8)',
              name: 'Claytone',
              id: '701154',
              sku: '557620',
              MFG: 'Edco',
            },
            {
              color: 'White(1)',
              name: 'White',
              id: '700007',
              sku: '555601',
              MFG: 'Cellwood',
            },
            {
              color: 'White(1)',
              name: 'White',
              id: '700008',
              sku: '555601',
              MFG: 'Mastic',
            },
            {
              color: 'White(1)',
              name: 'White',
              id: '700009',
              sku: '555601',
              MFG: 'KP',
            },
            {
              color: 'Dover White(1)',
              name: 'Dover White',
              id: '700010',
              sku: '555601',
              MFG: 'Variform',
            },
            {
              color: 'White Birch(1)',
              name: 'White Birch',
              id: '700011',
              sku: '555601',
              MFG: 'RMC',
            },
            {
              color: 'Bright White(1)',
              name: 'Bright White',
              id: '700012',
              sku: '555601',
              MFG: 'Quality Edge',
            },
            {
              color: 'White(1)',
              name: 'White',
              id: '700602',
              sku: '555692',
              MFG: 'Cellwood',
            },
            {
              color: 'White(1)',
              name: 'White',
              id: '700603',
              sku: '555692',
              MFG: 'Mastic',
            },
            {
              color: 'White(1)',
              name: 'White',
              id: '700604',
              sku: '555692',
              MFG: 'KP',
            },
            {
              color: 'Dover White(1)',
              name: 'Dover White',
              id: '700605',
              sku: '555692',
              MFG: 'Variform',
            },
            {
              color: 'White Birch(1)',
              name: 'White Birch',
              id: '700606',
              sku: '555692',
              MFG: 'RMC',
            },
            {
              color: 'Bright White(1)',
              name: 'Bright White',
              id: '700607',
              sku: '555692',
              MFG: 'Quality Edge',
            },
            {
              color: 'Sand(48)',
              name: 'Sand',
              id: '705505',
              sku: '557638',
              MFG: 'Cellwood',
            },
            {
              color: 'Desert Sand(48)',
              name: 'Desert Sand',
              id: '705506',
              sku: '557638',
              MFG: 'Mastic',
            },
            {
              color: 'Natural Oak(48)',
              name: 'Natural Oak',
              id: '705507',
              sku: '557638',
              MFG: 'KP',
            },
            {
              color: 'Sand(48)',
              name: 'Sand',
              id: '705508',
              sku: '557638',
              MFG: 'Royal Building Products',
            },
            {
              color: 'Sahara(48)',
              name: 'Sahara',
              id: '705509',
              sku: '557638',
              MFG: 'Foundry',
            },
            {
              color: 'Sand Dune(48)',
              name: 'Sand Dune',
              id: '705510',
              sku: '557638',
              MFG: 'Norandex',
            },
            {
              color: 'Sandstone Beige(34)',
              name: 'Sandstone Beige',
              id: '704809',
              sku: '555606',
              MFG: 'Certainteed',
            },
            {
              color: 'Pearl(34)',
              name: 'Pearl',
              id: '704810',
              sku: '555606',
              MFG: 'EP',
            },
            {
              color: 'Cottage White(34)',
              name: 'Cottage White',
              id: '704811',
              sku: '555606',
              MFG: 'Rollex',
            },
            {
              color: 'Birchwood(34)',
              name: 'Birchwood',
              id: '704812',
              sku: '555606',
              MFG: 'Heartland-Provia',
            },
            {
              color: 'Eggshell(34)',
              name: 'Eggshell',
              id: '704813',
              sku: '555606',
              MFG: 'Foundry',
            },
            {
              color: 'Beige(34)',
              name: 'Beige',
              id: '704814',
              sku: '555606',
              MFG: 'Norandex',
            },
            {
              color: 'Arbor Blend(200)',
              name: 'Arbor Blend',
              id: '711413',
              sku: '555616',
              MFG: 'Certainteed',
            },
            {
              color: 'Cypress(200)',
              name: 'Cypress',
              id: '711414',
              sku: '555616',
              MFG: 'EP',
            },
            {
              color: 'Sage(200)',
              name: 'Sage',
              id: '711415',
              sku: '555616',
              MFG: 'KP',
            },
            {
              color: 'Meadow(200)',
              name: 'Meadow',
              id: '711416',
              sku: '555616',
              MFG: 'RMC',
            },
            {
              color: 'Mountain Laurel(200)',
              name: 'Mountain Laurel',
              id: '711417',
              sku: '555616',
              MFG: 'Quality Edge',
            },
            {
              color: 'Arbor Blend(200)',
              name: 'Arbor Blend',
              id: '711523',
              sku: '555706',
              MFG: 'Certainteed',
            },
            {
              color: 'Cypress(200)',
              name: 'Cypress',
              id: '711524',
              sku: '555706',
              MFG: 'EP',
            },
            {
              color: 'Sage(200)',
              name: 'Sage',
              id: '711525',
              sku: '555706',
              MFG: 'KP',
            },
            {
              color: 'Meadow(200)',
              name: 'Meadow',
              id: '711526',
              sku: '555706',
              MFG: 'RMC',
            },
            {
              color: 'Mountain Laurel(200)',
              name: 'Mountain Laurel',
              id: '711527',
              sku: '555706',
              MFG: 'Quality Edge',
            },
            {
              color: 'Sterling Grey/Silverplate(16)',
              name: 'Sterling Grey/Silverplate',
              id: '702825',
              sku: '557625',
              MFG: 'Certainteed',
            },
            {
              color: 'Victorian Grey(16)',
              name: 'Victorian Grey',
              id: '702826',
              sku: '557625',
              MFG: 'Quality Edge',
            },
            {
              color: 'Sandstone Beige(34)',
              name: 'Sandstone Beige',
              id: '704965',
              sku: '555698',
              MFG: 'Certainteed',
            },
            {
              color: 'Pearl(34)',
              name: 'Pearl',
              id: '704966',
              sku: '555698',
              MFG: 'EP',
            },
            {
              color: 'Cottage White(34)',
              name: 'Cottage White',
              id: '704967',
              sku: '555698',
              MFG: 'Rollex',
            },
            {
              color: 'Birchwood(34)',
              name: 'Birchwood',
              id: '704968',
              sku: '555698',
              MFG: 'Heartland-Provia',
            },
            {
              color: 'Eggshell(34)',
              name: 'Eggshell',
              id: '704969',
              sku: '555698',
              MFG: 'Foundry',
            },
            {
              color: 'Beige(34)',
              name: 'Beige',
              id: '704970',
              sku: '555698',
              MFG: 'Norandex',
            },
          ],
          variationGroups: [
            {
              variationTypes: ['MFG', 'color'],
            },
            {
              variationTypes: ['size'],
            },
          ],
          variations: {
            color: {
              'Shadow(8)': ['557620', '557946'],
              'Sand Dune(48)': ['557961', '557638'],
              'Sandstone Beige(34)': ['555698', '555606'],
              'Castle Stone(59)': ['555608', '555700'],
              'Desert Clay(8)': ['557620', '557946'],
              'Sierra(8)': ['557620', '557946'],
              'Charcoal Grey(59)': ['555608', '555700'],
              'White Birch(1)': ['555601', '555692'],
              'Country Beige(11)': ['555695'],
              'Misty Taupe(97)': ['555704'],
              'Pebble Clay(97)': ['555704'],
              'Sand(48)': ['557961', '557638'],
              'Summer Suede(11)': ['555695'],
              'Smoke(59)': ['555608', '555700'],
              'Arbor Blend(200)': ['555706', '555616'],
              'Autumn Leaf(8)': ['557620', '557946'],
              'Natural Oak(48)': ['557961', '557638'],
              'Sahara(48)': ['557961', '557638'],
              'Cottage White(34)': ['555698', '555606'],
              'Pebble(8)': ['557620', '557946'],
              'Cape Cod Grey(59)': ['555608', '555700'],
              'Desert Sand(48)': ['557961', '557638'],
              'Rustic Clay(8)': ['557620', '557946'],
              'Sterling Grey/Silverplate(16)': ['557950', '557625'],
              'Weather Blend/Heather(59)': ['555608', '555700'],
              'Beige(34)': ['555698', '555606'],
              'Bright White(1)': ['555601', '555692'],
              'Natural Clay(97)': ['555704'],
              'Birchwood(34)': ['555698', '555606'],
              'Cypress(97)': ['555704'],
              'Victorian Grey(16)': ['557950', '557625'],
              'Sage(200)': ['555706', '555616'],
              'White(1)': ['555601', '555692'],
              'Graphite Grey(59)': ['555608', '555700'],
              'Paintable(30)': ['557957', '557633'],
              'Natural Clay(8)': ['557620', '557946'],
              'Taupe(97)': ['555704'],
              'Clay(8)': ['557620', '557946'],
              'Eggshell(34)': ['555698', '555606'],
              'Wheat(65)': ['555609', '555701'],
              'Pearl(34)': ['555698', '555606'],
              'Stratus(59)': ['555608', '555700'],
              'Claytone(8)': ['557620', '557946'],
              'Meadow(200)': ['555706', '555616'],
              'Khaki(8)': ['557620', '557946'],
              'Mountain Laurel(200)': ['555706', '555616'],
              'Sierra Brown(11)': ['555695'],
              'Cypress(200)': ['555706', '555616'],
              'Stone Mountain Clay(8)': ['557620', '557946'],
              'Clay(97)': ['555704'],
              'Greystone(59)': ['555608', '555700'],
              'Dover White(1)': ['555692', '555601'],
            },
            size: {
              '18" x 24"': [
                '557946',
                '557957',
                '555704',
                '555698',
                '555700',
                '555701',
                '557950',
                '557961',
                '555695',
                '555706',
                '555692',
              ],
              '12" x 18"': [
                '557638',
                '555616',
                '555606',
                '555601',
                '557625',
                '557620',
                '557633',
                '555608',
                '555609',
              ],
            },
            MFG: {
              Exteria: ['557620', '557946'],
              'Quality Edge': [
                '557946',
                '555616',
                '555704',
                '555601',
                '557625',
                '557620',
                '557950',
                '555695',
                '555706',
                '555692',
              ],
              'Gentek CA': ['557620', '557946'],
              KP: [
                '557638',
                '555616',
                '555704',
                '555601',
                '557961',
                '555706',
                '555692',
              ],
              'Heartland-Provia': ['555698', '555606'],
              Mitten: ['555608', '555700'],
              'Royal Building Products': ['557961', '557638'],
              Variform: ['557620', '557946', '555692', '555601'],
              'CT Vytec': ['557620', '555695', '557946', '555608', '555700'],
              RMC: ['555616', '555706', '555608', '555700', '555601', '555692'],
              EP: [
                '555704',
                '555616',
                '555606',
                '555698',
                '555700',
                '555701',
                '555695',
                '555706',
                '555608',
                '555609',
              ],
              Edco: ['557620', '557946'],
              Foundry: [
                '557620',
                '557961',
                '557638',
                '557946',
                '555606',
                '555698',
              ],
              Rollex: ['557620', '557946', '555606', '555698'],
              Certainteed: [
                '555616',
                '555606',
                '555698',
                '555700',
                '557625',
                '557950',
                '555706',
                '555608',
              ],
              'TRI-BUILT': ['557957', '557633'],
              'Allura ': ['555704'],
              'Gentek/Revere': ['557620', '557946'],
              Cellwood: [
                '557620',
                '557961',
                '557946',
                '557638',
                '555601',
                '555692',
              ],
              Norandex: [
                '557638',
                '557946',
                '555704',
                '555606',
                '555698',
                '555700',
                '557620',
                '557961',
                '555608',
              ],
              'Georgia Pacific': ['555704'],
              Mastic: [
                '557961',
                '557638',
                '555608',
                '555601',
                '555700',
                '555692',
              ],
              'CT Wolverine': ['555704'],
            },
          },
          variationKeyMFG: 'MFG',
          availableVariationCount: 3,
          highestPrioritySku: null,
          singleColorDisplay: 'Arbor Blend(200)',
          validSkuIdsMap: {},
          maxVariationGroupSize: 2,
          allVariationTypes: ['MFG', 'color', 'size'],
          currentVariations: {
            color: 'please_select',
            size: '12" x 18"',
            MFG: 'please_select',
          },
          currentSkuId: '555608',
          variationSteps: {
            showStep1: true,
            step2: {
              size: {
                '18" x 24"': [
                  '557957',
                  '557946',
                  '555704',
                  '555698',
                  '555700',
                  '555701',
                  '557950',
                  '557961',
                  '555695',
                  '555706',
                  '555692',
                ],
                '12" x 18"': [
                  '557638',
                  '555616',
                  '555606',
                  '555601',
                  '557625',
                  '557620',
                  '557633',
                  '555608',
                  '555609',
                ],
              },
            },
            showStep2: true,
            step1: {
              color: {
                'Shadow(8)': ['557620', '557946'],
                'Sand Dune(48)': ['557961', '557638'],
                'Sandstone Beige(34)': ['555698', '555606'],
                'Castle Stone(59)': ['555608', '555700'],
                'Desert Clay(8)': ['557620', '557946'],
                'Sierra(8)': ['557620', '557946'],
                'Charcoal Grey(59)': ['555608', '555700'],
                'White Birch(1)': ['555692', '555601'],
                'Country Beige(11)': ['555695'],
                'Misty Taupe(97)': ['555704'],
                'Pebble Clay(97)': ['555704'],
                'Sand(48)': ['557961', '557638'],
                'Summer Suede(11)': ['555695'],
                'Smoke(59)': ['555608', '555700'],
                'Arbor Blend(200)': ['555706', '555616'],
                'Autumn Leaf(8)': ['557620', '557946'],
                'Natural Oak(48)': ['557961', '557638'],
                'Sahara(48)': ['557961', '557638'],
                'Cottage White(34)': ['555698', '555606'],
                'Pebble(8)': ['557620', '557946'],
                'Cape Cod Grey(59)': ['555608', '555700'],
                'Desert Sand(48)': ['557961', '557638'],
                'Rustic Clay(8)': ['557620', '557946'],
                'Sterling Grey/Silverplate(16)': ['557950', '557625'],
                'Weather Blend/Heather(59)': ['555608', '555700'],
                'Beige(34)': ['555698', '555606'],
                'Bright White(1)': ['555601', '555692'],
                'Natural Clay(97)': ['555704'],
                'Birchwood(34)': ['555698', '555606'],
                'Cypress(97)': ['555704'],
                'Victorian Grey(16)': ['557950', '557625'],
                'Sage(200)': ['555706', '555616'],
                'White(1)': ['555601', '555692'],
                'Graphite Grey(59)': ['555608', '555700'],
                'Paintable(30)': ['557957', '557633'],
                'Natural Clay(8)': ['557620', '557946'],
                'Taupe(97)': ['555704'],
                'Clay(8)': ['557620', '557946'],
                'Eggshell(34)': ['555698', '555606'],
                'Wheat(65)': ['555609', '555701'],
                'Pearl(34)': ['555698', '555606'],
                'Stratus(59)': ['555608', '555700'],
                'Claytone(8)': ['557620', '557946'],
                'Meadow(200)': ['555706', '555616'],
                'Khaki(8)': ['557620', '557946'],
                'Mountain Laurel(200)': ['555706', '555616'],
                'Sierra Brown(11)': ['555695'],
                'Cypress(200)': ['555706', '555616'],
                'Stone Mountain Clay(8)': ['557620', '557946'],
                'Clay(97)': ['555704'],
                'Greystone(59)': ['555608', '555700'],
                'Dover White(1)': ['555692', '555601'],
              },
              MFG: {
                Exteria: ['557620', '557946'],
                'Quality Edge': [
                  '557946',
                  '555704',
                  '555616',
                  '555601',
                  '557625',
                  '557620',
                  '557950',
                  '555695',
                  '555706',
                  '555692',
                ],
                'Gentek CA': ['557620', '557946'],
                KP: [
                  '557638',
                  '555704',
                  '555616',
                  '555601',
                  '557961',
                  '555706',
                  '555692',
                ],
                'Heartland-Provia': ['555698', '555606'],
                Mitten: ['555608', '555700'],
                'Royal Building Products': ['557961', '557638'],
                Variform: ['557620', '557946', '555601', '555692'],
                'CT Vytec': ['557620', '555695', '557946', '555608', '555700'],
                RMC: [
                  '555616',
                  '555706',
                  '555608',
                  '555601',
                  '555692',
                  '555700',
                ],
                EP: [
                  '555616',
                  '555704',
                  '555606',
                  '555698',
                  '555700',
                  '555701',
                  '555695',
                  '555706',
                  '555608',
                  '555609',
                ],
                Edco: ['557620', '557946'],
                Foundry: [
                  '557620',
                  '557961',
                  '557638',
                  '557946',
                  '555606',
                  '555698',
                ],
                Rollex: ['557620', '557946', '555606', '555698'],
                Certainteed: [
                  '555616',
                  '555606',
                  '555698',
                  '555700',
                  '557625',
                  '557950',
                  '555706',
                  '555608',
                ],
                'TRI-BUILT': ['557957', '557633'],
                'Allura ': ['555704'],
                'Gentek/Revere': ['557620', '557946'],
                Cellwood: [
                  '557620',
                  '557961',
                  '557946',
                  '557638',
                  '555601',
                  '555692',
                ],
                Norandex: [
                  '557946',
                  '557638',
                  '555704',
                  '555606',
                  '555698',
                  '555700',
                  '557961',
                  '557620',
                  '555608',
                ],
                'Georgia Pacific': ['555704'],
                Mastic: [
                  '557961',
                  '557638',
                  '555608',
                  '555700',
                  '555692',
                  '555601',
                ],
                'CT Wolverine': ['555704'],
              },
            },
          },
        },
        skusVariation: null,
        variations: null,
        imageUrl: {
          thumbnail: '/images/large/555608_default_thumb.jpg',
          large: '/images/large/555608_default.jpg',
          swatch: '/images/large/555608_default_swatch.jpg',
        },
        productImageUrl: '/images/large/555608_default_thumb.jpg',
        unitPrice: 64.74,
        itemUnitPrice: 0,
        quantity: 40,
        itemOrProductDescription: 'TRI-BUILT 12" x 18" Rectangle Gable Vent 59',
        unitOfMeasure: 'PC',
        nickName: null,
        templateItemId: 'gi20340013',
        productOnErrorImageUrl: '/images/large/brand/tri-built_brand_thumb.jpg',
        productNumber: null,
        defaultUnitOfMeasure: 'PC',
        internalProductName: 'Rectangle Gable Vent',
        ATGItemMapping: null,
        itemSubTotal: 0,
        nonStockItem: false,
        sendDescriptionOnlyToMincron: false,
        lineComments: null,
        extendedDescription: null,
        hasBranchAvailability: false,
      },
      {
        itemNumber: '656457',
        itemType: null,
        sendToMincronDirectly: false,
        vendorColorId: null,
        pdpUrl:
          '/productDetail/C-656458?skuId=656457&Color=Barkwood&Dimension=13-1%2F4%22+x+39-3%2F8%22',
        available: true,
        description: null,
        productOrItemNumber: 'C-656458',
        subTotal: 0,
        productOrItemDescription: null,
        multiVariationData: {
          singleVariationDisplay: {
            color: 'Barkwood',
            size: '13-1/4" x 39-3/8"',
          },
          allOptionsSingle: false,
          skus: {
            '656457': {
              color: ['Barkwood'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '656458': {
              color: ['Birchwood'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '656460': {
              color: ['Hickory'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '656461': {
              color: ['Pewter Grey'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '656462': {
              color: ['Shakewood'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '656463': {
              color: ['Slate'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '656464': {
              color: ['Weathered Wood'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '673329': {
              color: ['Mission Brown'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '674168': {
              color: ['Hunter Green'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
            '693302': {
              color: ['Charcoal'],
              size: ['13-1/4" x 39-3/8"'],
              width: ['13-1/4"'],
              length: ['39-3/8"'],
            },
          },
          defaultSkuId: '656462',
          currentVendorColorId: null,
          variationKeyColor: 'color',
          vendorColors: [],
          variationGroups: [
            {
              variationTypes: ['color'],
            },
            {
              variationTypes: ['size'],
            },
          ],
          variations: {
            color: {
              'Hunter Green': ['674168'],
              'Mission Brown': ['673329'],
              Shakewood: ['656462'],
              'Weathered Wood': ['656464'],
              Birchwood: ['656458'],
              Barkwood: ['656457'],
              'Pewter Grey': ['656461'],
              Slate: ['656463'],
              Charcoal: ['693302'],
              Hickory: ['656460'],
            },
            size: {
              '13-1/4" x 39-3/8"': [
                '656462',
                '656461',
                '656464',
                '656463',
                '674168',
                '693302',
                '656457',
                '656458',
                '673329',
                '656460',
              ],
            },
          },
          variationKeyMFG: 'MFG',
          availableVariationCount: 1,
          highestPrioritySku: null,
          singleColorDisplay: 'Barkwood',
          validSkuIdsMap: {
            '656459': '693302',
          },
          maxVariationGroupSize: 1,
          allVariationTypes: ['color', 'size'],
          currentVariations: {
            color: 'Barkwood',
            size: '13-1/4" x 39-3/8"',
          },
          currentSkuId: '656457',
          variationSteps: {
            showStep1: true,
            step2: {
              size: {
                '13-1/4" x 39-3/8"': [
                  '656462',
                  '656461',
                  '656464',
                  '656463',
                  '693302',
                  '674168',
                  '656457',
                  '656458',
                  '673329',
                  '656460',
                ],
              },
            },
            showStep2: true,
            step1: {
              color: {
                'Hunter Green': ['674168'],
                'Mission Brown': ['673329'],
                Shakewood: ['656462'],
                'Weathered Wood': ['656464'],
                Birchwood: ['656458'],
                Barkwood: ['656457'],
                'Pewter Grey': ['656461'],
                Slate: ['656463'],
                Charcoal: ['693302'],
                Hickory: ['656460'],
              },
              MFG: null,
            },
          },
        },
        skusVariation: null,
        variations: null,
        imageUrl: {
          thumbnail: '/images/large/656457_default_thumb.jpg',
          large: '/images/large/656457_default.jpg',
          swatch: '/images/large/656457_default_swatch.jpg',
        },
        productImageUrl: '/images/large/656457_default_thumb.jpg',
        unitPrice: 45.5,
        itemUnitPrice: 0,
        quantity: 60,
        itemOrProductDescription:
          'GAF 13-1/4" x 39-3/8" Timberline HDZ&trade; Shingles with StainGuard Protection Barkwood',
        unitOfMeasure: 'BDL',
        nickName: null,
        templateItemId: 'gi20340012',
        productOnErrorImageUrl: '/images/large/brand/gaf_brand_thumb.jpg',
        productNumber: null,
        defaultUnitOfMeasure: 'BDL',
        internalProductName:
          'Timberline HDZ&trade; Shingles with StainGuard Protection',
        ATGItemMapping: null,
        itemSubTotal: 0,
        nonStockItem: false,
        sendDescriptionOnlyToMincron: false,
        lineComments: null,
        extendedDescription: null,
        hasBranchAvailability: true,
      },
    ],
    accountLegacyId: '280381',
    isAccountClosed: false,
    lastModifiedUser: {
      firstName: 'uat',
      lastName: 'submitter',
      emailAddress: null,
      cartLineItems: null,
      internalUser: false,
      rewardsEligible: false,
      lastSelectedAccount: null,
      profileId: null,
      userType: null,
      accountBranch: null,
    },
    templateId: 'gl92501052',
  },
  success: true,
  messages: null,
};
